apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
    group: {{ .Values.backend.group }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        group: {{ .Values.backend.group }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.container.image }}  
          ports:
            - containerPort: {{ .Values.backend.container.port }}
          envFrom:
            {{- range .Values.backend.container.config }}
            - configMapRef:
                name: {{ .name }}
            {{- end}}
          env:
            {{- range .Values.backend.container.env}}
            - name: {{ .key}}
              value: {{ .value}}
            {{- end}}
          resources:
            limits:
              memory: {{ .Values.resources.memory }}
              cpu: {{ .Values.resources.cpu }}